"""Filesystem scaffolding for ``streamtree init`` (stdlib only)."""

from __future__ import annotations

from pathlib import Path


def app_py_source(*, page_title: str, with_pages: bool = False) -> str:
    """Return generated ``app.py`` source (single-file ``render_app`` shell)."""
    title_literal = repr(page_title)
    if with_pages:
        return f'''"""StreamTree app (generated by ``streamtree init --with-pages``)."""

from __future__ import annotations

from streamtree import component, render_app
from streamtree.app import App
from streamtree.core.element import Element
from streamtree.elements import Page, Text, VStack
from streamtree.helpers import discover_pages, page_links


@component
def SidebarNav() -> Element:
    entries = discover_pages(__file__)
    if not entries:
        return VStack(Text("Add scripts under pages/ (e.g. 1_Hello.py)."))
    return VStack(Text("Pages"), *page_links(entries))


@component
def Main() -> Element:
    return Page(
        VStack(
            Text("Hello from StreamTree"),
            Text("Use the sidebar for multipage links. Run: streamtree run app.py"),
        )
    )


if __name__ == "__main__":
    render_app(
        App(
            page_title={title_literal},
            sidebar=SidebarNav(),
            body=Main(),
        )
    )
'''
    return f'''"""StreamTree app (generated by ``streamtree init``)."""

from __future__ import annotations

from streamtree import component, render_app
from streamtree.app import App
from streamtree.core.element import Element
from streamtree.elements import Page, Text, VStack


@component
def Main() -> Element:
    return Page(
        VStack(
            Text("Hello from StreamTree"),
            Text("Edit this file, then run: streamtree run app.py"),
        )
    )


if __name__ == "__main__":
    render_app(App(page_title={title_literal}, body=Main()))
'''


PAGE_ABOUT = '''"""Example multipage script (Streamlit ``pages/`` convention)."""

from __future__ import annotations

import streamlit as st

st.title("About")
st.caption("Generated by ``streamtree init --with-pages``.")
'''


def _validate_root(root: Path) -> Path:
    r = root.resolve()
    if r.exists() and not r.is_dir():
        msg = f"target path exists and is not a directory: {r}"
        raise ValueError(msg)
    return r


def write_init_project(
    root: Path,
    *,
    page_title: str,
    with_pages: bool,
    force: bool,
) -> list[Path]:
    """Write ``app.py`` and optionally ``pages/`` under ``root``.

    Returns paths of files written. Raises ``FileExistsError`` if a file would
    be overwritten and ``force`` is false.
    """
    r = _validate_root(root)
    r.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    app_path = r / "app.py"
    if app_path.exists() and not force:
        raise FileExistsError(str(app_path))
    app_path.write_text(
        app_py_source(page_title=page_title, with_pages=with_pages), encoding="utf-8"
    )
    written.append(app_path)

    if with_pages:
        pages_dir = r / "pages"
        pages_dir.mkdir(parents=True, exist_ok=True)
        about = pages_dir / "1_About.py"
        if about.exists() and not force:
            raise FileExistsError(str(about))
        about.write_text(PAGE_ABOUT, encoding="utf-8")
        written.append(about)

    return written


__all__ = ["app_py_source", "write_init_project"]
