"""Declarative layout and widget primitives."""

from streamtree.charts import AltairChart, Chart
from streamtree.core.element import Element, Fragment, fragment
from streamtree.elements.auth_gate import AuthGate
from streamtree.elements.layout import (
    Card,
    Columns,
    Dialog,
    ErrorBoundary,
    Expander,
    Form,
    Grid,
    HStack,
    Page,
    Popover,
    Portal,
    PortalMount,
    Routes,
    Sidebar,
    Spacer,
    SplitView,
    Tabs,
    VStack,
)
from streamtree.elements.ui_extra import (
    BottomDock,
    ColoredHeader,
    FloatingActionButton,
    MentionChip,
    SocialBadge,
    SocialBadgeKind,
    StyleMetricCards,
    Stoggle,
    TaggerRow,
    VerticalSpaceLines,
)
from streamtree.elements.widgets import (
    Button,
    Checkbox,
    DataFrame,
    Divider,
    Image,
    Markdown,
    NumberInput,
    PageLink,
    Selectbox,
    Subheader,
    Text,
    TextInput,
    Title,
)
from streamtree.tables import DataGrid
from streamtree.theme import Theme, ThemeRoot

__all__ = [
    "AltairChart",
    "AuthGate",
    "BottomDock",
    "Button",
    "Card",
    "Checkbox",
    "ColoredHeader",
    "Columns",
    "Chart",
    "DataFrame",
    "DataGrid",
    "Dialog",
    "Divider",
    "Element",
    "ErrorBoundary",
    "Expander",
    "FloatingActionButton",
    "Form",
    "Fragment",
    "Grid",
    "HStack",
    "Image",
    "Markdown",
    "MentionChip",
    "NumberInput",
    "Page",
    "PageLink",
    "Popover",
    "Portal",
    "PortalMount",
    "Routes",
    "Selectbox",
    "Sidebar",
    "SocialBadge",
    "SocialBadgeKind",
    "SplitView",
    "Spacer",
    "Stoggle",
    "StyleMetricCards",
    "Subheader",
    "Tabs",
    "TaggerRow",
    "Text",
    "TextInput",
    "Theme",
    "ThemeRoot",
    "Title",
    "VStack",
    "VerticalSpaceLines",
    "fragment",
]
